### ISSUE TITLE
Failed to install Script

### ISSUE THREAD

**Issue by RabbITCybErSeC** [amzn/zeek-plugin-s7comm#5]
Hi, 

I am trying to install zeek-plugin-s7comm through the zkg installer. However, the process failed. I checked the logs and obtained the following:

``` 
In file included from /opt/zeek/var/lib/zkg/clones/package/zeek-plugin-s7comm/src/S7comm.cc:1:
/opt/zeek/var/lib/zkg/clones/package/zeek-plugin-s7comm/src/S7comm.h:4:10: fatal error: analyzer/protocol/tcp/TCP.h: No such file or directory
    4 | #include "analyzer/protocol/tcp/TCP.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/Zeek-S7comm.linux-x86_64.dir/build.make:110: CMakeFiles/Zeek-S7comm.linux-x86_64.dir/src/S7comm.cc.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:300: CMakeFiles/Zeek-S7comm.linux-x86_64.dir/all] Error 2
```
Zeek Source Directory   : 
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0

System= Ubuntu 21.10
               zkg 2.12.0
               zeek version 4.2.0
Thank you for considering this issue, if any additional information is required please let me know.

**Comment by RabbITCybErSeC** [comment]
I think I found the issue. Unfortunately, the plugin version available on the `zkg` package manager is older than the current GitHub version. I manually cloned the GitHub repository into Zeek and build from there, which seems to work. Therefore, I suggest updating the package version according to the latest Github commit version. 

Thank you

**Comment by NothinRandom** [comment]
@thehoodbuddha,

It can take up to 24h for the sync to happen, so please try again if possible.  If the problem still persists, please let me know.  Thanks!
